# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/zybo_const.xdc

# Block Designs: bd/System/System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System || ORIG_REF_NAME==System} -quiet] -quiet

# IP: bd/System/ip/System_xlconstant_1_0/System_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlconstant_1_0 || ORIG_REF_NAME==System_xlconstant_1_0} -quiet] -quiet

# IP: bd/System/ip/System_dvi2rgb_0_1/System_dvi2rgb_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_dvi2rgb_0_1 || ORIG_REF_NAME==System_dvi2rgb_0_1} -quiet] -quiet

# IP: bd/System/ip/System_rgb2dvi_0_1/System_rgb2dvi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_rgb2dvi_0_1 || ORIG_REF_NAME==System_rgb2dvi_0_1} -quiet] -quiet

# IP: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0} -quiet] -quiet

# IP: bd/System/ip/System_fifo_generator_0_0/System_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_fifo_generator_0_0 || ORIG_REF_NAME==System_fifo_generator_0_0} -quiet] -quiet

# IP: bd/System/ip/System_fifo_generator_0_1/System_fifo_generator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_fifo_generator_0_1 || ORIG_REF_NAME==System_fifo_generator_0_1} -quiet] -quiet

# IP: bd/System/ip/System_fifo_generator_0_2/System_fifo_generator_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_fifo_generator_0_2 || ORIG_REF_NAME==System_fifo_generator_0_2} -quiet] -quiet

# IP: bd/System/ip/System_Video_Processing_Sys_0_0/System_Video_Processing_Sys_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_Video_Processing_Sys_0_0 || ORIG_REF_NAME==System_Video_Processing_Sys_0_0} -quiet] -quiet

# IP: bd/System/ip/System_RGB_to_Gray_0_0/System_RGB_to_Gray_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_RGB_to_Gray_0_0 || ORIG_REF_NAME==System_RGB_to_Gray_0_0} -quiet] -quiet

# IP: bd/System/ip/System_Shift_register_0_0/System_Shift_register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_Shift_register_0_0 || ORIG_REF_NAME==System_Shift_register_0_0} -quiet] -quiet

# IP: bd/System/ip/System_Shift_register_1_0/System_Shift_register_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_Shift_register_1_0 || ORIG_REF_NAME==System_Shift_register_1_0} -quiet] -quiet

# IP: bd/System/ip/System_Shift_register_2_0/System_Shift_register_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_Shift_register_2_0 || ORIG_REF_NAME==System_Shift_register_2_0} -quiet] -quiet

# XDC: bd/System/System_ooc.xdc
