webtalk_init -webtalk_dir /home/sergiu/Documents/Digilent/DDC/sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-05-06 03:29:03" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211608554_0_0_420" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "kncgvjsshda0h1f70rl3lmhsjn" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_23" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "23" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2810.413 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.248 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1557097958000" -context "sdk\\\\hardware/1557097958000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1557097958000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1557097958000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1557097958000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1557097958000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1557097958000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1557097958000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1557097958000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1557097958000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1557097958000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1557097958000"
webtalk_add_data -client sdk -key uid -value "1557098002000" -context "sdk\\\\bsp/1557098002000"
webtalk_add_data -client sdk -key hwid -value "1557097958000" -context "sdk\\\\bsp/1557098002000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1557098002000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1557098002000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1557098002000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1557102543628"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1557102543628"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1557102543628"
webtalk_add_data -client sdk -key DebugCount -value "133" -context "sdk\\\\bsp/1557102543628"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1557102543628"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1557102543628"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1557102543628"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1557102543628"
webtalk_transmit -clientid 2296132574 -regid "211608554_0_0_420" -xml /home/sergiu/Documents/Digilent/DDC/sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/sergiu/Documents/Digilent/DDC/sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/sergiu/Documents/Digilent/DDC/sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
